//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam1gpi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class test1gpiEntities : DbContext
    {
        public test1gpiEntities()
            : base("name=test1gpiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<ordersDetail> ordersDetail { get; set; }
        public virtual DbSet<person> person { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<productUnitMeasurement> productUnitMeasurement { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<sales> sales { get; set; }
        public virtual DbSet<settingProductSupply> settingProductSupply { get; set; }
        public virtual DbSet<supply> supply { get; set; }
        public virtual DbSet<unitMeasurement> unitMeasurement { get; set; }
        public virtual DbSet<supplyMovement> supplyMovement { get; set; }
    }
}
