//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam1gpi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ordersDetail
    {
        public int codOrderDetail { get; set; }
        public int codOrder { get; set; }
        [Display(Name = "Producto")]
        public int codProduct { get; set; }
        [Display(Name = "Cantidad")]
        [Range(1, 1000000, ErrorMessage = "Ingrese un diferente de cero")]
        public int quantity { get; set; }
    
        public virtual orders orders { get; set; }
        public virtual product product { get; set; }
    }
}
