//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam1gpi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class settingProductSupply
    {
        public int codSettingProductSupply { get; set; }
        [Display(Name = "Suministro")]
        public int codSupply { get; set; }
        [Display(Name = "Cantidad")]
        [Range(1, 1000000, ErrorMessage = "Ingrese un número diferente de cero")]
        public int quantity { get; set; }
        [Display(Name = "Producto - unidad de medida")]
        public int codProductUnitMeasurement { get; set; }
    
        public virtual productUnitMeasurement productUnitMeasurement { get; set; }
        public virtual supply supply { get; set; }
    }
}
